### ISSUE TITLE
Which salt to use for demagnetization cooling?

### ISSUE THREAD

**Issue by zmwangx** [stanford-physics108-2015/cryo#1]
We'll need to have a fairly specific idea (choice and reason) by Friday.

**Comment by marxwillia** [comment]
From reading Benford1994, it seems that one good possibility is CCA:

Salt: Chromic Caesium Alum (CCA)
Properties: J = 3/2, resists dehydration at room temperature

**Comment by bvlehm** [comment]
I'm fine with CCA, and it seems to be among the most common choices I've seen in the literature. I still don't fully understand how it compares with the materials discussed by Gschneider et al. But I think it would be appropriate to ask David about the availability of CCA; it certainly sounds like it will serve our purposes, so perhaps we have no need to look further unless there's a significant cost / lead time.

**Comment by zmwangx** [comment]
LGTM.

**Comment by zmwangx** [comment]
@bvlehm Ben, could you please post your bookmarked links here? (The ones for purchasing salts.)

**Comment by bvlehm** [comment]
@zmwangx Good idea. Here they are:

[CPA from Alfa Aesar](https://www.alfa.com/en/catalog/A11816) (note that it is "Frequently bought with" FAA)

[CPA from VWR](https://us.vwr.com/store/catalog/product.jsp?catalog_number=AAAA11816-36) (more reasonably priced than their FAA)

[CPA from Sigma-Aldrich](https://www.sigmaaldrich.com/catalog/search?term=7788-99-0&interface=CAS%20No.&N=0+&mode=partialmax&lang=en&region=US&focus=product)

[FAA from Alfa Aesar](https://www.alfa.com/en/catalog/A16105)

[FAA from Sigma-Aldrich](http://www.sigmaaldrich.com/catalog/search?term=7783-83-7&interface=CAS%20No.&N=0+&mode=partialmax&lang=en&region=US&focus=product) (both crystals and powders)

[FAA from VWR](https://us.vwr.com/store/catalog/product.jsp?catalog_number=JT1988-7) (large order only?)

[FAA from Oxford ChemServe](http://oxfordchemserve.com/ferric-ammonium-alum-100-g-recrystallised/) (small amount; lead time?)

**Comment by zmwangx** [comment]
It seems that we're fairly certain about CPA and FAA, so I'm closing this.
