### ISSUE TITLE
Final design

### ISSUE THREAD

**Issue by zmwangx** [stanford-physics108-2015/cryo#10]
This is a master issue for the final design. We can put some little thoughts and logistic stuff (there's a lot) here, but major technical issues should be created and discussed separately, and this issue will be blocked until all technical ones are cleared, currently:
- #4 Analytic calculation of cooling power;
- #7 Thermometer;
- #8 Heat switch design;
- #9 Heat conduction between salt pill and thermometer (and the competition with heat leak) — timescale estimates.

As a reminder, the deadlines are:
- **Fri 01/23/2015**: design review;
- **Mon 01/26/2015**: final drawings.

We have a lot of details to hammer out, and a lot of things to put into writing. And we don't have much time.

@bvlehm @marxwillia @rexgarland

**Comment by bvlehm** [comment]
I have added a basic vector drawing to the wiki page, where things should be to scale with reasonable accuracy.

@rexgarland, you mentioned you had some experience with SolidWorks. How difficult would it be to create an equivalent drawing there? It will probably be useful for us to have a real CAD model as we start designing the individual pieces. (That said, maybe this can wait until we are done with the design review.)

**Comment by zmwangx** [comment]
@bvlehm Thanks for the vector graphics. We do need to keep in mind that
- There are things going on outside the magnet (e.g., a heat sink);
- The heat switch design is subject to change;
- We might have switches on the wires (seems pretty hard to me, though).

One question that I haven't thought about until this point:
- How do we grow a cylindrical salt pill? Grow it on a cylindrical base?

**Comment by bvlehm** [comment]
@zmwangx:

> How do we grow a cylindrical salt pill? Grow it on a cylindrical base?

I'm not sure of the best way to deal with the salts in the form we get them. My impression from the TAs has been that we'll get the salt as a powder and mix the powder with epoxy to ensure thermal contact between the particles. We could let this mixture set inside the pill, which would set the shape—but then we need to work out how much space the epoxy itself is going to take up.

**Comment by zmwangx** [comment]
@bvlehm 

> we'll get the salt as a powder and mix the powder with epoxy to ensure thermal contact between the particles.

That makes sense. Downside: in that case I have the impression that we totally lose control over the heat conduction rate (the surface area between epoxy and salt is hard to estimate).

**Comment by bvlehm** [comment]
@zmwangx That's very true. It might be wise to see how it looks with a small sample at room temperature, but even that may not be very informative.

By the way, I agree that heat-switching the wires isn't easy, but I have some thoughts about how we might do it if we have to. Here's an example design:

![wireswitch](https://cloud.githubusercontent.com/assets/10425334/5791768/b3a98e88-9ea2-11e4-9f19-e56071fcf059.png)

In black: supports and a spring. In blue: epoxy. In green: a string. In orange: a copper plate. When we let go of the string, the spring would push the copper plate down, bridging the wires. The gap could be made longer to decrease thermal conduction.

**Comment by zmwangx** [comment]
@bvlehm I was thinking about something similar, but we need to heat-switch wires from both legs of the thermometer, so the design will have to be intricate in order to fit things into the narrow tube, with everything touching the right things and avoiding the wrong things.

**Comment by marxwillia** [comment]
@zmwangx  Is it necessary for us to have the heat switch for the thermometer wires inside the narrow tube?  I think it would work just as well to do outside of the magnet.

**Comment by zmwangx** [comment]
@marxwillia Good point. As long as we place the heat switch before we reach the heat sink in helium.

**Comment by bvlehm** [comment]
@marxwillia @zmwangx These are good thoughts. There are two more things I want to consider, as heat switch design goes:
1. We need to make sure that everything will still make a strong contact given thermal contraction, which might shift things around. In anything like the diagram above, we should probably smother the contacts in some kind of thermal paste so that minor shifts aren't a problem.
2. If we use any springs anywhere, we need to be aware of how the elasticity will be affected at sub-K temperatures. I don't think this should be a terribly large effect, but stronger springs may be a better idea.

**Comment by zmwangx** [comment]
Today's drawings (as of 4:30pm) are available in our Dropbox as `Images/20150129-final-drawings-v0.1.pdf`. There are certain changes that need to be made tonight; we'll talk in person so I won't list them here. You may also access the PDF file directly online at http://1drv.ms/1vc32nM.

**Comment by bvlehm** [comment]
Final drawings are now at `Images/final_drawings.pdf`. I know that Zhiming and Rex have signed off on them; @marxwillia, if you see anything you think should be changed in the diagrams, you can let me know up until tomorrow (Mon 2 Feb) morning around 9:00. I'll close this issue after we get final approval from Karl.

**Comment by zmwangx** [comment]
@bvlehm 

> Final drawings are now at `Images/final_drawings.pdf`.

Also as `drawings.pdf` inside the git repo. I committed it in since Marc replied to the email thread and didn't raise any objection. Anyway, we can make changes if necessary.

**Comment by bvlehm** [comment]
Karl has the final drawings and will contact us if anything comes up.
