### ISSUE TITLE
Vacuum Chamber Design

### ISSUE THREAD

**Issue by rexgarland** [stanford-physics108-2015/cryo#11]
From 1/20 meeting with Patrick:

Some options:
1. indium seal: doesn't require a vacuum pump, soft metal at low temperatures
2. "cone seal:" uses vacuum grease and a vacuum pump to create a seal between two metals

**Comment by zmwangx** [comment]
From Marc and I's meeting with machinist Karlheinz on Friday, Jan 23, we'll use indium seal(s), since cone seals need very precise machining (perfect cone).

**Comment by zmwangx** [comment]
Finalized. See final drawings.
