### ISSUE TITLE
Magnet Electronics

### ISSUE THREAD

**Issue by rexgarland** [stanford-physics108-2015/cryo#12]
Issues raised in the 1/20 meeting with Patrick:
1. How much power will be dissipated into the Helium when we coil the wires (Patrick suggested that this is minimal, ~nA current into superconducting magnet)?
2. How fast can we switch on the magnet without the magnet "going normal?"

**Comment by rexgarland** [comment]
@stanford-physics108-2015/owners 

crude calculation:

6.8 Amps \* 0.25 Henry / 0.09 Volts ~ 20 seconds to energize magnet (using emf = -L dI/dt)
(current and voltage ratings from [AMI specs](https://coursework.stanford.edu/access/content/group/W15-PHYSICS-108-01/Hardware%20Info%20--%20Design%20and%20Data/Osheroff_Lect4.pdf) on coursework)

**Comment by zmwangx** [comment]
We'll need to check in with Rick to see what kind of current sources we have. (Patrick suggested that we might have special current sources designed precisely for sc magnets.)

**Comment by bvlehm** [comment]
I think all of these issues have been resolved. If not, heaven help us tomorrow.
