### ISSUE TITLE
Starting temperature and superfluidity

### ISSUE THREAD

**Issue by bvlehm** [stanford-physics108-2015/cryo#14]
There is one critical uncertainty in our design: we can be fairly sure of our ability to keep out gaseous helium, but influx of superfluid LHe is unpredictable. If LHe floods our vacuum flask, we may have an unacceptable level of thermal contact between the salt pill and the bath, which could ruin the experiment.

Therefore, I suggest that we plan to do one test at 4.2 K (above the superfluid transition), followed by a test at ~1.5 K. With this approach, we have a little more time to figure out what we're doing with a 4.2 K run, since the helium will boil off less rapidly. While we can't confidently predict what will happen starting from 4.2 K, we might still see something interesting. And if we don't, we just go right on to pumping.

A caveat: we should not plan on doing a 4.2 K test _after_ a 1.5 K test. Any helium that snuck in while superfluid will not be able to leave, and thus, we could still have extra thermal conductivity.

**Comment by zmwangx** [comment]
Sure. Just for the record, according to [Wikipedia](https://en.wikipedia.org/wiki/Liquid_helium), the superfluid transition temperature of He-4 at saturated vapor pressure is **2.17K**.
