### ISSUE TITLE
Monitoring electronics

### ISSUE THREAD

**Issue by bvlehm** [stanford-physics108-2015/cryo#15]
We need to design and implement two electronic systems apart from the magnet power supply:
1. Thermometer reader
2. Heat switch closure detector

The design was originally meant to be our task for week 4, but we were occupied with mechanical design details. However, we now have some extra time while we wait for parts to come back from the shop; I suggest we use it to get every aspect of the electrical setup and python interface working, even if things are alligator clipped.

**Comment by marxwillia** [comment]
I uploaded a gpib module for monitoring the oscilloscope.  We can add other instruments to it as needed.
