### ISSUE TITLE
Find spring for heat switch

### ISSUE THREAD

**Issue by bvlehm** [stanford-physics108-2015/cryo#16]
We need to choose a spring for our heat switch. The diameter must be no smaller than 7 mm, and no greater than 15 mm. Overall length is presumably not a problem if we can cut a long spring to size. It is critical, however, that we choose the spring constant appropriately: too small and we get bad thermal contact, but too large and we risk damaging the apparatus or breaking the control string.

**Comment by zmwangx** [comment]
We can pick a long spring with low spring constant, and compress it more. This way, given the same pressing force in the on position, the force it takes to raise the plate by a certain delta h is smaller, making the string less likely to break.

**Comment by zmwangx** [comment]
We've discarded the idea of using a spring.
