### ISSUE TITLE
Starting temperature?

### ISSUE THREAD

**Issue by rexgarland** [stanford-physics108-2015/cryo#2]
@bvlehm @marxwillia @zmwangx

**Comment by zmwangx** [comment]
@bvlehm  @marxwillia

**Comment by rexgarland** [comment]
From lecture: helium gas flow cryostats (evaporative cooling) bring us down to ~1.5 K

**Comment by zmwangx** [comment]
Now it's pretty clear that the starting temperature should be as low as liquid helium could get us down to (since we're doing one shot), so I'm closing this. Open a new and more focused issue if starting temperature proves to be a concern.
