### ISSUE TITLE
Understand ADR S-T Curve

### ISSUE THREAD

**Issue by marxwillia** [stanford-physics108-2015/cryo#5]
What is the lowest possible temperature that we can bring the load down to?  Most importantly, is it possible to repeat the ADR cycle to get successively smaller final temperatures?  Look in the dropbox at the files labelled Successive-ST-Curve.pdf to see the ST curve that we would like to have.

@marxwillia @bvlehm  @rexgarland  @zmwangx

**Comment by bvlehm** [comment]
In meeting with the TAs, we have confirmed that repeating the ADR cycle requires multi-stage design, which is impractical for our limited resources. We will therefore stick with a single-shot design.

Before we close this issue, let's perform a basic thermal calculation.

**Comment by zmwangx** [comment]
We have done a reasonable single-shot calculation (thanks to Ben), and we're not going back. Closing.
