### ISSUE TITLE
Initial drawings

### ISSUE THREAD

**Issue by bvlehm** [stanford-physics108-2015/cryo#6]
We need schematic drawings of the apparatus. We don't need them to be detailed, but they should cover all of the major parts. Due: Friday.

@marxwillia @zmwangx @rexgarland @bvlehm

**Comment by bvlehm** [comment]
@rexgarland I think you wrote down some of the magnet dimensions from our meeting yesterday. Could you write this into the wiki page [here](https://github.com/stanford-physics108-2015/cryo/wiki/Magnets)?

**Comment by rexgarland** [comment]
done

**Comment by zmwangx** [comment]
Link to wiki page:
https://github.com/stanford-physics108-2015/cryo/wiki/Drawings

Current version:
<img src="http://i.imgur.com/LOTnfWH.jpg" height="400" width="300" />

**Comment by bvlehm** [comment]
@zmwangx I've reviewed the labeling on the Wiki page and made a small edit. This diagram should be all we need for now, so I'm closing this issue. If I have a minute tomorrow, I may vectorize this diagram.

**Comment by zmwangx** [comment]
@bvlehm Cool. I'm pretty bad at Illustrator or tikz or svg stuff, so I can't help (unless necessary). Sorry about that.
