### ISSUE TITLE
Heat switch design

### ISSUE THREAD

**Issue by zmwangx** [stanford-physics108-2015/cryo#8]
In yesterday's (01/16/2015) meeting we discussed the design of the heat switch. We had some ideas on the spot (and from our previous discussions); if I recall correctly we had two on the board:

![](http://i.imgur.com/qHSfBhN.png)

David promised to look into the "standard" designs, and Alex promised to consult an expert colleague.

Someone also had the brilliant idea of integrating heat switches as parts of the wiring so that heat is not leaked in from the wires during the equilibration stage. The resistance of the heat switch might prove to be a problem though.

We have to finalize the heat switch design in the next week.

@marxwillia @rexgarland @bvlehm

**Comment by rexgarland** [comment]
From 1/20 meeting with Patrick: issue feeding a fishing line into the vacuum chamber to move the heat switch. His alternative: superconducting heat switch within vacuum chamber. His reasoning: commercial superconducting heat switches are relatively cheap and would be easy to install. His hesitance: DGG mentioned that using a superconducting heat switch might be an "entire project on its own."

**Comment by zmwangx** [comment]
Finalized. See final drawings.
